name: Validation

on: workflow_call

jobs:
  application_test:
    name: Application Test
    runs-on: ubuntu-latest

    services:
      dynamodb:
        image: amazon/dynamodb-local
        ports:
          - 8000:8000
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node environment
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Create DynamoDB app tables
        run: npm run script:dynamodb_tables

      - name: Run Tests
        run: npm run test
        
